version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/dataset-catalog-gui"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/dataset-catalog-gui-v2"
    schedule:
      interval: "weekly"
      day: "sunday"    
